os: linux
dist: xenial
language: python
python:
  - "3.6"
sudo: false

env:
      global:
        # Doctr deploy key for cdcooper84/test-ownership
        - secure: "kF27terF/dbmgZqDm/wgu0VpmyR0PWPU15qyMFxLIH7WDGXXujkBQI2qRctWXUDKB9uql3rK89uyCzoYpAl+cGqBvuU5Dp2LeLayenjkJFnfHyo/2jUWPdj9mSnjXPv+/RQfqqr2AtRslCeGmItUFqNj39U28YJUoPccXloOeTz8icPLC8lcxBAzuxzaD1I5toHZgZ5I7S0crzieP7YapjAR7YycbGI5FouVNJ6FHuOb8wRjuXQ1V6lQzAFW2Y/iTrCPAKAAlvdgrU18lpqb2jhyAmJ6ta1cj/kzFNjbrY+OLgjoZ1ZhC2Tg8tiToyB9aYE+kkJEn6QSpsbp+L2tA4Nbuq5oZByHyrC6/R8A9r31qQmNjmKqhPH8Iyc4dRZdg60QVIWDerqxO3zoE/6C7ruVYFbdynDOhxy7W/KQ8HBkTt6eSKA+M7CnHR8b2G7o4aS306vNmzPihQXNXnFDnYZigG/MX0nO8QJf587G+7qYefegX4V4Sy6Qvjxi44Wx6XF7uHkRwgwf0h+BHKWYAe/2AKkDjVRBzezF4jDiYe/NGfPmUkUyNZ0mpppVvcmUqGPCjNU0ZkJUL0ACHt/NnbBXzPK60O2qACeJPMBt9aIlPn6pfJ2lMohuXEcYs00l2ng0yDO4J4YryBG7Re6ylw7S45LW3mzgMGzkNXbU/FI="

before_install:
  - MINICONDA_DIR=$HOME/miniconda3
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $MINICONDA_DIR
  - echo "source $MINICONDA_DIR/etc/profile.d/conda.sh" >> $HOME/.bashrc
  - source $HOME/.bashrc
  - conda activate
  - conda config --set always_yes yes
  - conda config --add channels conda-forge

install:
  - conda env create --name=py36 --file=environment.yaml
  - conda activate py36
  - pip install doctr
  - pip install mkdocs python-markdown-math

script:
  - mkdocs build --clean --verbose
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      doctr deploy --built-docs=_site .;
    else
      doctr deploy --no-require-master --built-docs=_site "docs-$TRAVIS_BRANCH";
    fi

notifications:
  email: false

branches:
  tags: true
  only:
    - master
    - develop
