os: linux
dist: xenial
language: python
python:
  - "3.6"
sudo: false

before_install:
  - MINICONDA_DIR=$HOME/miniconda3
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $MINICONDA_DIR
  - echo "source $MINICONDA_DIR/etc/profile.d/conda.sh" >> $HOME/.bashrc
  - source $HOME/.bashrc
  - conda activate
  - conda config --set always_yes yes
  - conda config --add channels conda-forge

install:
  - conda env create --name=py36 --file=environment.yaml
  - conda activate py36
  - pip install doctr
  - pip install mkdocs python-markdown-math

script:
  - mkdocs build --clean --verbose
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      doctr deploy --built-docs=_site .;
    else
      doctr deploy --no-require-master --built-docs=_site "docs-$TRAVIS_BRANCH";
    fi

notifications:
  email: false

branches:
  tags: true
  only:
    - master
    - develop